# Generated by Django 5.2.17 on 2026-09-17 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arxiv_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('abstract', models.TextField(blank=True)),
                ('entry_url', models.URLField(blank=True, max_length=1000)),
                ('pdf_url', models.URLField(blank=True, max_length=1000)),
                ('pdf_path', models.CharField(blank=True, max_length=1000)),
                ('download_status', models.CharField(choices=[('pending', '대기'), ('ready', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('section_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='scholar.paper')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('download', '다운로드'), ('extract', '본문 추출'), ('summarize', '요약'), ('translate', '번역')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '대기'), ('running', '실행 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='scholar.paper')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='scholar.paper')),
            ],
            options={
                'ordering': ['-saved_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'paper'), name='unique_library_entry_user_paper')],
            },
        ),
        migrations.CreateModel(
            name='PaperSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_order', models.PositiveIntegerField()),
                ('section_title', models.CharField(blank=True, max_length=500)),
                ('section_text', models.TextField()),
                ('section_html', models.TextField(blank=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scholar.paper')),
            ],
            options={
                'ordering': ['section_order'],
                'constraints': [models.UniqueConstraint(fields=('paper', 'section_order'), name='unique_paper_section_order')],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_type', models.CharField(choices=[('summary', '요약문'), ('full_text', '전체 본문')], default='summary', max_length=20)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('source_language', models.CharField(default='en', max_length=20)),
                ('target_language', models.CharField(default='ko', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='scholar.paper')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='scholar.papersummary')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('summary', 'translation_type', 'target_language'), name='unique_summary_translation_language')],
            },
        ),
    ]
