# Generated by Django 5.2.17 on 2026-09-17 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='translation',
            name='unique_summary_translation_language',
        ),
        migrations.AlterField(
            model_name='translation',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='scholar.papersummary'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('paper', 'translation_type', 'target_language'), name='unique_paper_translation_language'),
        ),
    ]
