# Generated by Django 5.2.17 on 2026-09-22 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_remove_translation_unique_summary_translation_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=64)),
                ('query', models.TextField()),
                ('status', models.CharField(choices=[('pending', '대기'), ('running', '실행 중'), ('completed', '완료'), ('failed', '실패'), ('needs_input', '추가 입력 필요')], default='pending', max_length=20)),
                ('plan', models.JSONField(blank=True, default=list)),
                ('node_history', models.JSONField(blank=True, default=list)),
                ('response', models.TextField(blank=True)),
                ('papers', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
