# Generated by Django 5.2.17 on 2026-09-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0003_supervisorrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorrun',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
