# Generated by Django 5.2.17 on 2026-09-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0004_supervisorrun_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorrun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
