"""
Django settings for django_config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import random
import sys
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
SRC_DIR = PROJECT_ROOT / "src"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

# LangGraph Supervisor(src/orchestration)는 내부에서 `from orchestration...`,
# `from tools...` 형태로 형제 모듈을 부르므로 src/ 자체도 import 루트로 등록한다.
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))


load_dotenv(PROJECT_ROOT / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 수정: 환경 변수가 없을 경우 안전한 폴백 키 자동 생성 (배포 에러 방지)

RUNPOD_API_KEY = os.getenv('RUNPOD_API_KEY', '').strip()
RUNPOD_POD_ID = os.getenv('RUNPOD_POD_ID', '').strip()
RUNPOD_API_URL = os.getenv('RUNPOD_API_URL', '').strip()

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-fallback-key-" + "".join(random.choices("abcdefghijklmnopqrstuvwxyz0123456789", k=20))
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

# 모든 호스트 접속 허용 (배포 및 테스트 단계 권장)
ALLOWED_HOSTS = [
    '52.79.195.18',
    'localhost',
    '127.0.0.1',
    'skn33.iptime.org',
    '.skn33-project.store',
    'skn33-project.store',
    '*',
]

CSRF_TRUSTED_ORIGINS = [
    'http://skn33-project.store:8000',
    'http://*.skn33-project.store:8000',
    'http://52.79.195.18:8000',
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "scholar.apps.ScholarConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# settings.py 내 DATABASES 설정 부분 확인 및 보정
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'paper_scholar'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'skn33.iptime.org'),
        'PORT': int(os.getenv('DB_PORT', 33062)),  # 반드시 int로 캐스팅
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# [핵심 수정] BrowsableAPIRenderer를 1순위로 명시하여 브라우저 대화형 UI 강제 출력
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 인증되지 않은 API 요청은 401을 반환하되, browsable API의 세션 로그인과
        # Basic 인증도 계속 지원한다.
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 프론트가 {count, results} 모양을 기대한다. 이 설정이 빠지면 목록이
    # 맨 배열로 나가고, 화면에서 results 를 읽다가 터진다.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        (
            "http://localhost:5173,http://127.0.0.1:5173,"
            "http://localhost:3000,http://127.0.0.1:3000,"
            "https://skn33-project.store"
        ),
    ).split(",")
    if origin.strip()
]

# 2. Ollama Base URL 결정 로직 (우선순위: 명시적 URL > POD ID 기반 프록시 URL > 로컬 폴백)
if RUNPOD_API_URL:
    # RUNPOD_API_URL이 직접 설정된 경우 우선 적용
    OLLAMA_BASE_URL = RUNPOD_API_URL.rstrip('/')
elif RUNPOD_POD_ID:
    # POD ID가 존재할 경우 RunPod 11434 포트 프록시 주소 자동 조합
    OLLAMA_BASE_URL = f"https://{RUNPOD_POD_ID}-11434.proxy.runpod.net"
else:
    # 환경 변수가 없을 경우 개발용 로컬 주소로 폴백
    OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://localhost:11434').rstrip('/')

# 3. 사용할 기본 Ollama 모델 식별자
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'qwen2.5:3b')

# 4. RunPod 프록시 인증을 위한 HTTP 헤더 딕셔너리 생성
OLLAMA_HEADERS = {}
if RUNPOD_API_KEY:
    # RunPod 프록시 엔드포인트 통과를 위한 Bearer 인증 토큰 주입
    OLLAMA_HEADERS['Authorization'] = f"Bearer {RUNPOD_API_KEY}"