"""
Django settings for django_config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import random
import sys
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
SRC_DIR = PROJECT_ROOT / "src"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

# LangGraph Supervisor(src/orchestration)는 내부에서 `from orchestration...`,
# `from tools...` 형태로 형제 모듈을 부르므로 src/ 자체도 import 루트로 등록한다.
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

# .env 환경 변수 파일 로드 (프로젝트 루트 및 backend 경로 우선 탐색)
load_dotenv(PROJECT_ROOT / ".env")
load_dotenv(BASE_DIR / ".env")

# ==============================================================================
# RunPod & Security Settings
# ==============================================================================
# 1. RunPod 시크릿 환경 변수 로드
RUNPOD_API_KEY = os.getenv('RUNPOD_API_KEY', '').strip()
RUNPOD_POD_ID = os.getenv('RUNPOD_POD_ID', '').strip()
RUNPOD_API_URL = os.getenv('RUNPOD_API_URL', '').strip()

# 2. Django SECRET_KEY 및 DEBUG 설정
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-fallback-key-" + "".join(random.choices("abcdefghijklmnopqrstuvwxyz0123456789", k=20))
)

DEBUG = os.environ.get("DEBUG", "True").strip().lower() in ("true", "1", "t")

# 3. 환경 변수 기반 네트워크/도메인 보안 설정 동적 파싱
# ALLOWED_HOSTS: 백엔드 서버가 허용할 호스트 및 IP 리스트 파싱
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "52.79.195.18,localhost,127.0.0.1,skn33.iptime.org,.skn33-project.store,skn33-project.store,*"
    ).split(",")
    if host.strip()
]

# CSRF_TRUSTED_ORIGINS: 외부 도메인 및 포트로부터의 안전한 POST 요청 허용
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://skn33-project.store:8000,http://*.skn33-project.store:8000,http://52.79.195.18:8000"
    ).split(",")
    if origin.strip()
]

# CORS_ALLOWED_ORIGINS: 프론트엔드 출처(Origin) 허용 목록 파싱
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        (
            "http://localhost:5173,http://127.0.0.1:5173,"
            "http://localhost:3000,http://127.0.0.1:3000,"
            "https://skn33-project.store"
        ),
    ).split(",")
    if origin.strip()
]


# ==============================================================================
# Application definition
# ==============================================================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "scholar.apps.ScholarConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_config.wsgi.application'


# ==============================================================================
# Database Configuration
# ==============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'paper_scholar'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'skn33.iptime.org'),
        'PORT': int(os.getenv('DB_PORT', 33062)),  # 포트 번호 정수형 변환 필수
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 10,
        },
    }
}


# ==============================================================================
# Password Validation
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# Internationalization
# ==============================================================================
LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# ==============================================================================
# Static files (CSS, JavaScript, Images)
# ==============================================================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# Django REST Framework & JWT
# ==============================================================================
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# ==============================================================================
# RunPod Ollama Endpoint Resolution
# ==============================================================================
# 1. Base URL 결정 로직 (명시적 URL > POD ID 기반 프록시 URL > 로컬 주소 폴백)
if RUNPOD_API_URL:
    OLLAMA_BASE_URL = RUNPOD_API_URL.rstrip('/')
elif RUNPOD_POD_ID:
    OLLAMA_BASE_URL = f"https://{RUNPOD_POD_ID}-11434.proxy.runpod.net"
else:
    OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://localhost:11434').rstrip('/')

# 2. 기본 인퍼런스 모델 식별자
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'qwen2.5:3b')

# 3. RunPod 프록시 인증 헤더 구성
OLLAMA_HEADERS = {}
if RUNPOD_API_KEY:
    OLLAMA_HEADERS['Authorization'] = f"Bearer {RUNPOD_API_KEY}"